require_relative "./upcomingMovies/version"
require_relative "./upcomingMovies/movie"
require_relative "./upcomingMovies/cli"
require_relative "./upcomingMovies/person"
require_relative "./upcomingMovies/persons/actor"
