require_relative "./upcomingMovies/version"
require_relative "./upcomingMovies/person"
require_relative "./upcomingMovies/persons/actor"
require_relative "./upcomingMovies/helper"
require_relative "./upcomingMovies/movie"
require_relative "./upcomingMovies/scrape"
require_relative "./upcomingMovies/cli"
